### ISSUE TITLE
Add informative Errors

### ISSUE THREAD

**Issue by MitchTurner** [MitchTurner/naumachia#6]
Right now we're just using strings

**Comment by Ch1n3du** [comment]
Hi, I'd love to help with this if I can, do you have anything in mind for the errrors. I've been reading through the repo and it looks really cool

**Comment by MitchTurner** [comment]
Do you have experience using [thiserror](https://docs.rs/thiserror/latest/thiserror/)?

I haven't put a ton of thought into it, but essentially I was just gonna replace the error type in crate::error::Result with some empty enum and let the compiler tell me what to fix. This is a "good first issue" but it might be a bit of busy work.

The one thing I want to stress is that the domain should define the shape of the errors, but allow the implementers of the ports to extend the error types. Something like:

```
#[derive(Error, Debug)]
pub enum Error {
    #[error("Not enough {0} to fulfill transaction]
    InsufficientFunds(Policy),
    ...
    TxoRecord(TxoRecordError),
    ...
}

pub enum TxoRecordError {
    #[error("Failed to retrieve UTxOs: {0}")]
    FailedToRetrieveUTxOs(Box<dyn Error>),
    ...
}

...
```
So, essentially, the interfaces, like `TxORecord` or `ValidatorCode` will each have their own error type with some flexibility for the implementers, and then those can each be included in a set of core, domain errors.

Idk if that makes sense. I'm happy to give more examples. Just writing this on the fly.

**Comment by MitchTurner** [comment]
Also open to ways we could chunk up the work into multiple PRs.

**Comment by Ch1n3du** [comment]
> So, essentially, the interfaces, like `TxORecord` or `ValidatorCode` will each have their own error type with some flexibility for the implementers, and then those can each be included in a set of core, domain errors.
> 
> Idk if that makes sense. I'm happy to give more examples. Just writing this on the fly.

I think I get what you mean, have on main `Error` enum and it should have variants like `TxORecord(TxORecordError)` where the `TxORecordError` type allow for more flexibility when adding more error cases for those specific areas? Also I wanted to ask what exactly `TxORecord` is meant to represent, I guessed an onchain address but not sure.

**Comment by Ch1n3du** [comment]
Also I wanted to ask why `Policy` is an `Option<Address>`

**Comment by MitchTurner** [comment]
`TxORecord` is my name for the abstraction of the Blockchain. I don't think it's a great name, but I just chose something (I'm open to suggestions). I didn't go with `Blockchain` because that's just an implementation detail; the domain of Naumachia doesn't care about it being a blockchain or a centralized ledger. All it cares about is that there are UTxOs owned by different addresses, essentially. Hence `TxORecord`.

So, currently, I just have an `InMemoryRecord` and a `LocalPersistedRecord` that are useful for tests and for writing front-ends without reaching out to the chain.

**Comment by MitchTurner** [comment]
> I think I get what you mean, have on main Error enum and it should have variants like TxORecord(TxORecordError) where the TxORecordError type allow for more flexibility when adding more error cases for those specific areas?

Sounds like we're on the same page. Each interface can have its own error and that way the implementer of that interface can add relevant errors that the core domain can't know about. i.e. The `LocalPersistedRecord` would return file-system errors, etc.

**Comment by MitchTurner** [comment]
>Also I wanted to ask why Policy is an Option<Address>

I also considered creating my own enum for `Policy`:
enum Policy {
    ADA,
    NativeToken(Address)
}

But it's kinda weird, since ADA is just `""`, so maybe neither is right.

This doesn't even cover TokenName stuff, which Naumachia has no concept of yet. 

I want to land on whatever is easiest to reason about within someone's SC. "Wishful driven design." As long as the information is conserved between conversions, of course--at the end of the day, it needs to be able to get converted to the on-chain representation.

As you can tell, a lot of this is in flux, but I've gone out of my way to put things behind interfaces and aliases so changing them in the future will have minimal impact.

**Comment by MitchTurner** [comment]
I just did a search of all the `trait`s. 

Probably `SCLogic` needs its own error. 

`SmartContractTrait` is a little different since that's the trait we provide to our consumers to mock Naumachia as a whole. It should should use the core error for that reason.

>I'm thinking of just modelling the interface errors after the trait functions following your example.

Awesome. And if we decide we want something different in the future we can change it. 

The library is still very much in exploration mode. I just wanted to get a working prototype out to the world so people could see what I had in mind and start contributing.

**Comment by MitchTurner** [comment]
I'd recommend having the trait errors live with the traits, btw.

**Comment by Ch1n3du** [comment]
I wanted to ask if this looks right
```rust
#[derive(Debug, Error)]
pub enum TxORecordError {
    #[error("Insufficient amount of {0:?}")]
    InsufficientAmountOf(Policy),
    #[error("Failed to retrieve outputs at {0:?}: {1:?}")]
    FailedToRetrieveOutputsAt(Address, Box<dyn std::error::Error>),
}

```

**Comment by MitchTurner** [comment]
I think so. I'd have to see there specific uses. Feel free to put a PR up and I can see how you're using them.

You could prolly get away with doing just one of the trait errors for now, just as a test run. You'll just need to `.map_err` them into the core error type.

**Comment by Ch1n3du** [comment]
Also not sure how to type the fields of the `SCLogicError` as it's generic
```rust
#[derive(Debug, Error)]
pub enum SCLogicError {
    // TODO Don't know how to constrain the type for these fields
    #[error("Failed to handle endpoint {0:?}")]
    FailedToHandleEndpoint(Box<dyn error::Error>),
    // TODO Not sure if this is right but not fully sure how the error for a failed lookup should look
    #[error("Failed to lookup: {0:?}")]
    FailedToLookup(Box<dyn error::Error>)
}

```

**Comment by Ch1n3du** [comment]
I will send a pr but here's an example of me using the `TxORecordError` in the `select_inputs_for_one` method
```rust
        for (policy, amt) in values.iter() {
            if let Some(available) = address_values.remove(policy) {
                if amt <= &available {
                    let remaining = available - amt;
                    remainders.push((remaining, address.clone(), policy.clone()));
                } else {
                    return Err(Error::TxORecord(TxORecordError::InsufficientAmountOf(
                        policy.to_owned(),
                    )));
                }
            } else {
                return Err(Error::TxORecord(TxORecordError::InsufficientAmountOf(
                    policy.to_owned(),
                )));
            }
        }
        let other_remainders: Vec<_> = address_values
            .into_iter()
            .map(|(policy, amt)| (amt, address.clone(), policy))
            .collect();
        remainders.extend(other_remainders);
        Ok((all_available_outputs, remainders))
    }
```

**Comment by MitchTurner** [comment]
>Also not sure how to type the fields of the SCLogicError as it's generic

Ah. Prolly use an assoc type for that as well. I'm getting a bit of a smell from all the types on the trait... but still seems right for now.

So you don't need to write that Error... but each of the impls will need one added.

**Comment by MitchTurner** [comment]
> I will send a pr but here's an example of me using the TxORecordError in the select_inputs_for_one method
Sweet. Yeah. this is essentially what I had in mind for now.

**Comment by Ch1n3du** [comment]
Also had slight issue backend module, will just create a `Box<dyn std::error::Error>` for the error not quite sure what is going in this snippet:

![Screenshot from 2022-08-09 21-39-47](https://user-images.githubusercontent.com/38131869/183756523-44a8dfeb-9b3c-4d5c-aa22-dc01e13cd95b.png)

**Comment by Ch1n3du** [comment]
Not sure if this is ideal
![Screenshot from 2022-08-09 21-46-39](https://user-images.githubusercontent.com/38131869/183757686-a2b7cac8-6391-48ab-a299-df965135c312.png)

**Comment by MitchTurner** [comment]
>Also had slight issue backend module, will just create a Box<dyn std::error::Error> for the error not quite sure what is going in this snippet:

This is just saying that there is no `From` impl for those traits. The return `Error` type doesn't match the expected `Error` type for that function.

At least, I think that's what's happening on quick glance.

**Comment by MitchTurner** [comment]
>Not sure if this is ideal

It's looking pretty good. Is there something I'm missing :P

**Comment by Ch1n3du** [comment]
> > Also had slight issue backend module, will just create a Box for the error not quite sure what is going in this snippet:
> 
> This is just saying that there is no `From` impl for those traits. The return `Error` type doesn't match the expected `Error` type for that function.
> 
> At least, I think that's what's happening on quick glance.

Sorry didn't give context. when I use the error type I defined like so: 

![Screenshot from 2022-08-09 22-20-20](https://user-images.githubusercontent.com/38131869/183764377-ffbf6adc-2c79-4f8a-9540-025713011ec8.png)

It throws an error

![Screenshot from 2022-08-09 22-21-16](https://user-images.githubusercontent.com/38131869/183764365-80915a4f-c31e-49f8-bd8c-233383173a59.png)

**Comment by MitchTurner** [comment]
Yeah. You're trying to pass the `Output` as an `dyn Error`. Instead, say:
```
    InputDoesNotExist(Output<Datum>)
```
Or, to make your life easier:
```
   InputDoesNotExist(String)
```
and just include the `tx_i.id()`.
